"""Право перетаскивания окна без рамки: core:window:allow-start-dragging в capabilities.

Узор Tauri 2 (tauri 2.12.1, permissions/window/autogenerated/reference.md):
`data-tauri-drag-region` из окна зовёт `plugin:window|start_dragging`, и вызов
проходит только с правом `core:window:allow-start-dragging`. Набор `core:default`
(в нём `default` ядра `core:window`) этого права НЕ несёт — без явной строки
перетаскивание в собранном окне молча не работает (замечание владельца
2026-10-06: «ну окно не могу двигать»). Кнопки свернуть/развернуть/закрыть —
свои команды Rust, прав не просят: они мертвы отдельно от этого права.

Проверка читает конфигурацию прямо: без окна и движка.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CAPS = os.path.join(ROOT, "src-tauri", "capabilities", "default.json")
CONF = os.path.join(ROOT, "src-tauri", "tauri.conf.json")

DRAG = "core:window:allow-start-dragging"


def check():
    if not os.path.isfile(CAPS):
        return 1, f"capability-файла нет: {CAPS} — ядро Tauri окну не разрешено вовсе"
    with open(CAPS, encoding="utf-8") as handle:
        caps = json.load(handle)
    with open(CONF, encoding="utf-8") as handle:
        conf = json.load(handle)
    permissions = caps.get("permissions", [])
    if "core:default" not in permissions:
        listed = ", ".join(str(one) for one in permissions)
        return 1, f"в capabilities/default.json нет core:default; есть {listed}"
    if DRAG not in permissions:
        listed = ", ".join(str(one) for one in permissions)
        return 1, (
            "окно не двигается: в capabilities/default.json нет "
            f"{DRAG} — у Tauri 2 core:default его не несёт; есть {listed}"
        )
    named = conf.get("app", {}).get("security", {}).get("capabilities")
    if named is not None and caps.get("identifier") not in named:
        return 1, f"tauri.conf.json подключает наборы {named} — набора default среди них нет"
    return 0, f"перетаскивание разрешено: core:default и явное право {DRAG} в capabilities/default.json"


if __name__ == "__main__":
    print(check()[1])
    sys.exit(check()[0])
